services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: tranglhoc
      MYSQL_DATABASE: tranglhoc
      MYSQL_USER: tranglhoc
      MYSQL_PASSWORD: tranglhoc
    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
  app:
    container_name: app
    image: tranglhoc
    ports:
      - "8081:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tranglhoc"
      - "SPRING_DATASOURCE_USERNAME=tranglhoc"
      - "SPRING_DATASOURCE_PASSWORD=tranglhoc"
    depends_on:
      - db

volumes:
  db_data:

